### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by jnfeinstein** [WealthBar/angular-d3#27]
I was thinking about making something exactly like this, and some of the roadmap features are on my todo list (i.e. bubble charts, mouse events).  I just want to make sure that it's still under active development, since I see that its been a while since most of the library was built.

**Comment by chrisnicola** [comment]
Yes, we have not needed any major features in a bit but we actively use it for https://www.wealthbar.com and will continue to develop it as we need things.

We do have a couple of things we've done for WealthBar that are not part of AngularD3 which are just extra directive. I'll probably backport them soon when I have some time. Most are related to labeling including one for an animated mouse-over legend.

**Comment by joel-nyansa** [comment]
Thanks for the update.  Looking forward to working with this library!

**Comment by jnfeinstein** [comment]
Thanks for the update. Looking forward to working with this library!
