### ISSUE TITLE
`bower.json` references non-existent files

### ISSUE THREAD

**Issue by jakubmal** [WealthBar/angular-d3#32]
Hey, firstly kudos for building this!
The problem is: `bower.json` references `"main": "dist/angularD3.js",` but it is not shipped as a part of the Bower package.

Would you mind fixing that?

**Comment by chrisnicola** [comment]
No problem, my bad, I've been updating this for webpack so if you use NPM you'll fine the npm module `angular_d3` is a bit better to work with. I'll correct this right away though.

Cheers!

**Comment by jakubmal** [comment]
This is great! Thanks!

**Comment by alexspark** [comment]
I'm running `bower install https://github.com/WealthBar/angular-d3.git\#0.0.35
` and i'm still not seeing the dist directory. any tips?

**Comment by alexspark** [comment]
I'm not too familiar with Bower, but perhaps you need to remove the "dist" directory from the bower.json file.

**Comment by chrisnicola** [comment]
@alexspark I'm not sure if this will work but I've updated the ignore and retagged. Let me know.

**Comment by alexspark** [comment]
@chrisnicola We're almost there. Can you remove the comma on line 11 in the bower.json to make it valid json. I'm getting an `unexpected token ]` error when I bower install

**Comment by chrisnicola** [comment]
Done

**Comment by alexspark** [comment]
That worked. Thank you!
