### ISSUE TITLE
Hover / touch 

### ISSUE THREAD

**Issue by DefunctExodus** [WealthBar/angular-d3#33]
First off great module.

I noticed you had a task for tool tips , but it was fairly dated so I am just curious if this is still something you are planning on adding in.
Thanks

**Comment by chrisnicola** [comment]
Yes we do have some plans. We actually have custom chartController extensions we use on wealthbar.com for this, but they are not generic enough to add to the AngularD3 project.

I'll gladly accept pull requests though.

**Comment by chrisnicola** [comment]
Closing this, not because we are not doing it, just because it isn't currently an Issue.

I will likely revisit this after the conversion to Angular 2. If you have any questions or want to see the code we use I'm happy to share it.

**Comment by DefunctExodus** [comment]
Sorry this has been on my list to respond to, just in the midst of learning
golang in order to switch from node.

I would like to see some of the code you use for a possible place to start
but I am also going to look at moving to angular 2.
