### ISSUE TITLE
Please provide a real demo

### ISSUE THREAD

**Issue by sweisman** [WealthBar/angular-d3#39]
Instead of cleverly combining all the JS and CSS into single minified files, can you do what most other widgets do and provide actual demos that provide a simple model to follow to use the widget? I have no idea what the actual usage of this widget is by looking at the "demo" you provide.

**Comment by chrisnicola** [comment]
Not at the moment no. I currently don't have time to improve the demo and most of my development time is now focused on the Angular 2 version: https://github.com/wealthbar/a2d3.

If you need you can see how the examples are constructed by looking through the source code here: https://github.com/WealthBar/angular-d3/blob/master/app/scripts/main_view.html

Which you will note is already mentioned in the README: _"Documentation will be forthcoming as things develop but for now you will have to rely on a quick reading of the code."_

I di completely agree that documentation and examples could and should be greatly improved, (a statement that would be true of most projects), however the way you have framed this here comes across as basically just a complaint and there is nothing concrete proposed in terms of how or where the documentation should be improved. Even when you suggest that it should be done like most other "widgets" do you have suggested no examples of this which would have been helpful.

Your complain however is duly noted, but as there is nothing here that is really that helpful, I'm going to close this with the acknowledgment that I agree better documentation would be great. If you wish to submit a more detailed proposal, or a pull request with improved documentation I would be happy to consider this further in the future, time permitting.
